name: Proxy Scraper Automation

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write  # Allow pushing changes to the repository

jobs:
  scrape-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Ensure Directory for Script
      run: |
        cd $GITHUB_WORKSPACE  # Ensure the script is executed in the correct directory

    - name: Run Proxy Scraper
      run: |
        python main.py  # Run your scraper script to update proxies.txt

    - name: Commit and Push Updated Proxies
      run: |
        git config --global user.name "zebbern"
        git config --global user.email "zebbern@users.noreply.github.com"
        git add proxies.txt
        git commit -m "Updated proxies.txt via automation"
        git push
