name: Proxy Scraper Automation

on:
  schedule:
    - cron: '0 */6 * * *' 
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  scrape-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Ensure Directory for Script
      run: |
        cd $GITHUB_WORKSPACE

    - name: Run Proxy Scraper
      run: |
        python3 main.py

    - name: Commit and Push Updated Proxies
      run: |
        git config --global user.name "zebbern"
        git config --global user.email "zebbern@users.noreply.github.com"
        git add proxies.txt
        git commit -m "Updated proxies.txt via automation"
        git push
